using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Xml;

/// <summary>
/// Checks the mod's XML before the build can look like it worked.
///
/// Besiege does not report an XML it dislikes in any way you would notice: the
/// block is simply absent from the toolbar, which looks like a dozen other
/// faults. Two things go wrong, and both are caught here.
///
/// **It has to parse.** An XML comment may not contain two hyphens in a row,
/// which prose written with a dash produces easily.
///
/// **A block has to carry the elements Besiege insists on.** `BasePoint` is the
/// one that bites: the loader says "Block must contain BasePoint element!" to the
/// log and gives up on the file. Nine blocks written from scratch, without one,
/// all failed to load at once.
///
/// **A block's module has to name the mod that owns it**, through a `modid`
/// matching `Mod.xml`'s own `ID`. Without it the block loads, appears in the
/// toolbar, and has nothing to customise -- the module never attaches, so none of
/// its mapper controls exist. That ID is generated by the game on first load, so
/// a fresh clone starts with none and every block XML is wrong until it is
/// stamped in; this catches that rather than leaving it to be discovered in game.
///
/// **A module element has to supply every attribute the module class requires.**
/// Besiege's `Serialization.Validate` checks the members that do *not* carry
/// `[DefaultValue]` and rejects the whole block XML over any one the element
/// omitted. That is the rule replicated below, read out of the module source
/// itself so the two cannot drift: a field with `[DefaultValue]` is optional, a
/// field without it is required in every element of that kind.
/// </summary>
static class XmlCheck
{
    /// <summary>Elements Besiege refuses a block without.</summary>
    static readonly string[] BlockRequires =
    {
        "ID", "Name", "Mesh", "Texture", "Colliders", "BasePoint", "AddingPoints"
    };

    public static int Main(string[] args)
    {
        int bad = 0;
        string modId = ModId(args);
        Dictionary<string, string> resources = Resources(args);
        Schema schema = Schema.Read(args);
        int checkedFiles = 0;

        for (int i = 0; i < args.Length; i++)
        {
            if (args[i].EndsWith(".cs"))
            {
                continue;                       // the module source, read above
            }
            checkedFiles++;
            XmlDocument doc = new XmlDocument();
            try
            {
                doc.Load(args[i]);
            }
            catch (Exception e)
            {
                Console.Error.WriteLine("  " + args[i] + ": " + e.Message);
                bad++;
                continue;
            }

            XmlElement root = doc.DocumentElement;
            if (root == null || root.Name != "Block")
            {
                continue;                       // Mod.xml and anything else
            }
            for (int r = 0; r < BlockRequires.Length; r++)
            {
                if (root.SelectSingleNode(BlockRequires[r]) == null)
                {
                    Console.Error.WriteLine("  " + args[i] + ": no <"
                                            + BlockRequires[r] + "> element");
                    bad++;
                }
            }

            // A block wears a mesh and a texture by name, and Besiege answers a
            // name it does not know with a block that has no shape. The names are
            // in one file and the resources in another, so they are checked
            // against each other here rather than in the game.
            bad += Wears(root, "Mesh", resources, args[i]);
            bad += Wears(root, "Texture", resources, args[i]);

            XmlNode modules = root.SelectSingleNode("Modules");
            if (modules != null && modId != null)
            {
                for (int m = 0; m < modules.ChildNodes.Count; m++)
                {
                    XmlElement module = modules.ChildNodes[m] as XmlElement;
                    if (module == null)
                    {
                        continue;
                    }
                    bad += schema.Check(module, args[i]);

                    string owner = module.GetAttribute("modid");
                    if (owner != modId)
                    {
                        Console.Error.WriteLine("  " + args[i] + ": <" + module.Name
                            + "> has modid=\"" + owner + "\", but Mod.xml says \""
                            + modId + "\"");
                        bad++;
                    }

                    // The panel's title says which block this is, and it says it
                    // from here: the modding API's only name for a block is the id
                    // of the mod that owns it. Two places, so they are checked
                    // against one another rather than trusted.
                    XmlNode named = root.SelectSingleNode("Name");
                    string family = module.GetAttribute("block");
                    if (named != null && family != named.InnerText.Trim())
                    {
                        Console.Error.WriteLine("  " + args[i] + ": <" + module.Name
                            + "> has block=\"" + family + "\", but the block is called \""
                            + named.InnerText.Trim() + "\"");
                        bad++;
                    }
                }
            }
        }
        if (bad > 0)
        {
            return 1;
        }
        Console.WriteLine("XML check: " + checkedFiles + " file(s) parse, blocks complete"
                          + schema.Summary() + ".");
        return 0;
    }

    /// <summary>
    /// Checks that what a block says it wears is declared in Mod.xml, and that the
    /// file behind it is really there.
    /// </summary>
    static int Wears(XmlElement root, string kind,
                     Dictionary<string, string> resources, string path)
    {
        XmlElement worn = root.SelectSingleNode(kind) as XmlElement;
        if (worn == null)
        {
            return 0;                       // the missing-element check has it
        }
        string name = worn.GetAttribute("name");
        string file;
        if (!resources.TryGetValue(kind + ":" + name, out file))
        {
            Console.Error.WriteLine("  " + path + ": <" + kind + " name=\"" + name
                + "\"> is not a " + kind + " Mod.xml declares");
            return 1;
        }
        // Mod.xml's paths are relative to the mod's Resources folder, not to the
        // manifest beside it.
        string here = Path.Combine(
            Path.Combine(Path.GetDirectoryName(Path.GetFullPath(path)), "Resources"),
            file.Replace('\\', Path.DirectorySeparatorChar));
        if (!File.Exists(here))
        {
            Console.Error.WriteLine("  " + path + ": " + kind + " \"" + name
                                    + "\" points at " + file + ", which is not there");
            return 1;
        }
        return 0;
    }

    /// <summary>Every mesh and texture Mod.xml declares, as kind:name -> path.</summary>
    static Dictionary<string, string> Resources(string[] args)
    {
        Dictionary<string, string> found = new Dictionary<string, string>();
        for (int i = 0; i < args.Length; i++)
        {
            if (!args[i].EndsWith("Mod.xml"))
            {
                continue;
            }
            try
            {
                XmlDocument doc = new XmlDocument();
                doc.Load(args[i]);
                XmlNode list = doc.DocumentElement.SelectSingleNode("Resources");
                if (list == null)
                {
                    continue;
                }
                foreach (XmlNode node in list.ChildNodes)
                {
                    XmlElement res = node as XmlElement;
                    if (res == null || (res.Name != "Mesh" && res.Name != "Texture"))
                    {
                        continue;
                    }
                    found[res.Name + ":" + res.GetAttribute("name")] = res.GetAttribute("path");
                }
            }
            catch (Exception)
            {
                // The parse check above reports it.
            }
        }
        return found;
    }

    /// <summary>The mod's own ID, or null before the game has written one.</summary>
    static string ModId(string[] args)
    {
        for (int i = 0; i < args.Length; i++)
        {
            if (!args[i].EndsWith("Mod.xml"))
            {
                continue;
            }
            try
            {
                XmlDocument doc = new XmlDocument();
                doc.Load(args[i]);
                XmlNode id = doc.DocumentElement.SelectSingleNode("ID");
                if (id != null && id.InnerText.Length > 0)
                {
                    return id.InnerText;
                }
            }
            catch (Exception)
            {
                // The parse error is reported by the main loop.
            }
        }
        return null;
    }
}


/// <summary>
/// Besiege's required-attribute rule, read out of the module source.
///
/// Serialization.Validate checks every member that does not carry
/// [DefaultValue], and rejects the whole block XML over a single one the element
/// did not supply. Rather than restate which attributes are required -- a list
/// that would quietly go stale -- this reads the [Xml*] and [DefaultValue]
/// markers off the module's own fields, so the check is always the code's rule.
///
/// The parse is deliberately shallow: it recognises the shape the module source
/// is written in, not C#. That is enough, and it fails loudly rather than
/// silently if it ever stops matching -- an element kind it did not find a class
/// for is simply not checked, which Summary() reports.
/// </summary>
class Schema
{
    /// <summary>Class name -> attributes that class requires.</summary>
    readonly Dictionary<string, List<string>> required =
        new Dictionary<string, List<string>>();

    /// <summary>XML element name -> the class it deserialises into.</summary>
    readonly Dictionary<string, string> elements = new Dictionary<string, string>();

    bool loaded;

    /// <summary>Reads every .cs among the arguments. Others are ignored.</summary>
    public static Schema Read(string[] args)
    {
        Schema s = new Schema();
        for (int i = 0; i < args.Length; i++)
        {
            if (!args[i].EndsWith(".cs"))
            {
                continue;
            }
            try
            {
                s.ReadSource(File.ReadAllLines(args[i]));
                s.loaded = true;
            }
            catch (Exception e)
            {
                Console.Error.WriteLine("  " + args[i] + ": " + e.Message);
            }
        }
        return s;
    }

    void ReadSource(string[] lines)
    {
        string cls = null;
        List<string> pending = new List<string>();

        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i].Trim();
            if (line.Length == 0 || line.StartsWith("//"))
            {
                continue;                       // comments never break a run
            }

            Match c = Regex.Match(line, @"^(?:public\s+)?class\s+(\w+)");
            if (c.Success)
            {
                cls = c.Groups[1].Value;
                required[cls] = new List<string>();
                pending.Clear();
                continue;
            }

            if (line.StartsWith("["))
            {
                pending.Add(line);
                continue;
            }

            Match f = Regex.Match(line, @"^public\s+(\S+)\s+(\w+)\s*[=;]");
            if (f.Success && cls != null)
            {
                Field(cls, f.Groups[1].Value, pending);
            }
            pending.Clear();
        }
    }

    void Field(string cls, string type, List<string> attributes)
    {
        string xmlAttribute = null, itemName = null, itemType = null;
        bool optional = false;

        for (int i = 0; i < attributes.Count; i++)
        {
            string a = attributes[i];
            if (a.StartsWith("[DefaultValue"))
            {
                optional = true;
            }
            else if (a.StartsWith("[XmlAttribute"))
            {
                xmlAttribute = Quoted(a);
            }
            else if (a.StartsWith("[XmlArrayItem") || a.StartsWith("[XmlElement"))
            {
                itemName = Quoted(a);
                Match t = Regex.Match(a, @"typeof\(\s*([\w\.]+)\s*\)");
                itemType = t.Success ? t.Groups[1].Value : null;
            }
        }

        if (xmlAttribute != null && !optional)
        {
            required[cls].Add(xmlAttribute);
        }
        if (itemName != null)
        {
            // An explicit typeof() wins; otherwise the element is of the array's
            // own type, which is how the module declares its lists.
            elements[itemName] = itemType != null
                ? itemType
                : type.Replace("[]", "").Trim();
        }
    }

    /// <summary>The first double-quoted string in an attribute, or null.</summary>
    static string Quoted(string attribute)
    {
        Match m = Regex.Match(attribute, "\"([^\"]*)\"");
        return m.Success ? m.Groups[1].Value : null;
    }

    /// <summary>
    /// Checks one module element and everything under it, and returns how many
    /// required attributes were missing.
    /// </summary>
    public int Check(XmlElement module, string path)
    {
        if (!loaded)
        {
            return 0;
        }
        return Walk(module, path);
    }

    int Walk(XmlElement element, string path)
    {
        int bad = 0;
        for (int i = 0; i < element.ChildNodes.Count; i++)
        {
            XmlElement child = element.ChildNodes[i] as XmlElement;
            if (child == null)
            {
                continue;
            }

            string cls;
            List<string> want;
            if (elements.TryGetValue(child.Name, out cls)
                && required.TryGetValue(cls, out want))
            {
                for (int a = 0; a < want.Count; a++)
                {
                    if (!child.HasAttribute(want[a]))
                    {
                        Console.Error.WriteLine("  " + path + ": <" + child.Name
                            + "> has no " + want[a] + "=\"...\", which " + cls
                            + " requires (give the field a [DefaultValue] to make"
                            + " it optional)");
                        bad++;
                    }
                }
            }
            bad += Walk(child, path);
        }
        return bad;
    }

    /// <summary>What the schema check actually covered, for the success line.</summary>
    public string Summary()
    {
        if (!loaded)
        {
            return " (no module source given; attributes unchecked)";
        }
        int n = 0;
        foreach (KeyValuePair<string, string> e in elements)
        {
            if (required.ContainsKey(e.Value))
            {
                n += required[e.Value].Count;
            }
        }
        return ", " + n + " required module attribute(s) present";
    }
}
